### ISSUE TITLE
Introducing CSS/Favicon (Requires SPIFFS)

### ISSUE THREAD

**Issue by XenoXilus** [hamishcunningham/fishy-wifi#14]
Once SPIFFS is implemented, CSS and Favicon customisation will be much easier to implement.

**Comment by layerzerolabs** [comment]
Good start - in order to support issue #12 can you try using [ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer) to provide a way to serve from SPIFFS please? Also please assign yourself to this issue, and also add the labels esp32 and Enhancement (helps us keep track as the numbers of issues grows...) Ta!

**Comment by hamishcunningham** [comment]
I think I've seen SPIFFS in use somewhere recently... ESPAsyncWebServer definitely a good thing for the future, but not sure how mature it is at present. Definitely a good track to look into though!

**Comment by layerzerolabs** [comment]
Can I ask @XenoXilus to choose this or issue #10 to prioritise and un-assign yourself from the other one? It helps keep track of things ta!

**Comment by XenoXilus** [comment]
Righty~ @layerzerolabs I've kept myself on #10
